services:

  user_service_rest:
    container_name: usr-srv-rest
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 9000:9000
    environment:
      PORT: 9000
      API: "REST"

  user_service_grpc:
    container_name: usr-srv-grpc
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 20001:20001
    environment:
      PORT: 20001
      API: "GRPC"

  websocket_service:
    container_name: ws-srv 
    build:
      context: .
      dockerfile: Dockerfile.ws
    restart: always
    ports: 
      - 2000:2000
