services:

  usr-srv-rest:
    container_name: user_service_rest
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 9000:9000
    environment:
      PORT: 9000
      API: "REST"

  
  usr-srv-grpc:
    container_name: user_service_grpc 
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 20001:20001
    environment:
      PORT: 20001
      API: "GRPC"
      ACCESS_SECRET: "secret"
      REFRESH_SECRET: "secret"

  chat-srv:
    container_name: chat_service
    build:
      context: .
      dockerfile: Dockerfile.ws
    restart: always
    ports: 
      - 2000:2000
    environment:
      PORT: 2000
      AUTH_SERVICE: "usr-srv-grpc:20001"

  notif-srv:
    container_name: notif_service
    build:
      context: .
      dockerfile: Dockerfile.notif
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
      AUTH_SERVICE: "usr-srv-grpc:20001"
