services:

  user_service_rest:
    container_name: usr-srv-rest
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 9000:9000
    env_file:
      - path: ./user/.env
        required: false

  user_service_grpc:
    container_name: usr-srv-grpc
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 20001:20001
    environment:
      API: "GRPC"

  websocket_service:
    container_name: ws-srv 
    build:
      context: .
      dockerfile: Dockerfile.ws
    restart: always
    ports: 
      - 2000:2000
