services:

  user_service:
    container_name: usr-srv
    build:
      context: ./user
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 9000:9000
    env_file:
      - path: .env
        required: false

  websocket_service:
    container_name: ws-srv 
    build:
      context: ./websocket
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 2000:2000
