services:

  usr-srv-rest:
    container_name: user_service_rest
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 9000:9000
    environment:
      PORT: 9000
      API: "REST"

  
  usr-srv-grpc:
    container_name: user_service_grpc 
    build:
      context: .
      dockerfile: Dockerfile.user
    restart: always
    ports: 
      - 20001:20001
    environment:
      PORT: 20001
      API: "GRPC"
      ACCESS_SECRET: "secret"
      REFRESH_SECRET: "secret"

  chat-srv:
    container_name: chat_service
    build:
      context: .
      dockerfile: Dockerfile.ws
    restart: always
    ports: 
      - 2000:2000
    environment:
      PORT: 2000
      AUTH_SERVICE: "usr-srv-grpc:20001"

  notif-srv:
    container_name: notif_service
    build:
      context: .
      dockerfile: Dockerfile.notif
    ports: 
      - 3000:3000
    environment:
      PORT: 3000
      AUTH_SERVICE: "usr-srv-grpc:20001"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9095:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 400
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/400:/kafka

  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "9096:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://localhost:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 401
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/401:/kafka

  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "9097:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 402
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./kafka_data/402:/kafka
